// Crash recovery for the notebook.
//
// Pyodide can run a browser tab out of memory on a large frame, and people
// close tabs by accident. Losing an hour of work to either is unacceptable, so
// the notebook keeps a copy of itself in this browser's local storage after
// every edit and offers it back on the next visit. Sources always survive;
// outputs are trimmed (and charts dropped) to stay inside the storage quota.
// Nothing leaves the device — localStorage is per-origin and never uploaded.
import type { NotebookCell } from './notebook';

const KEY = 'exceltools.notebook.draft.v1';
const ENABLED_KEY = 'exceltools.notebook.draft.enabled';
/** Table rows kept per output in the draft — the full result is one re-run away. */
const DRAFT_ROWS = 50;
const MAX_STDOUT = 4000;

export interface NotebookDraft {
  cells: NotebookCell[];
  /** Names of the tables that were registered, to explain what must be re-added. */
  tables: string[];
  savedAt: number;
}

/** Strip a draft down in stages until it fits the quota. */
function trim(cells: NotebookCell[], level: number): NotebookCell[] {
  return cells.map((c) => {
    const out: NotebookCell = { kind: c.kind, source: c.source };
    if (level >= 3) return out; // sources only
    if (c.execCount !== undefined) out.execCount = c.execCount;
    if (c.error) out.error = c.error;
    if (c.stdout) out.stdout = c.stdout.slice(0, MAX_STDOUT);
    if (level >= 2 || !c.outputs) return out;
    const kept = c.outputs
      // Charts are large; they are regenerated by re-running the cell.
      .filter((o) => o.type !== 'image')
      .map((o) => (o.type === 'table' ? { ...o, rows: o.rows.slice(0, DRAFT_ROWS) } : o));
    if (kept.length) out.outputs = kept;
    return out;
  });
}

/**
 * Whether drafts may be kept at all. On by default, but a shared or tightly
 * governed machine can turn it off — the rest of the suite writes nothing to
 * disk, and this is the one place that does.
 */
export function isDraftEnabled(): boolean {
  try {
    return localStorage.getItem(ENABLED_KEY) !== 'off';
  } catch {
    return false;
  }
}

/** Turn drafts on or off; turning them off deletes anything already stored. */
export function setDraftEnabled(on: boolean): void {
  try {
    localStorage.setItem(ENABLED_KEY, on ? 'on' : 'off');
  } catch {
    /* storage blocked — drafts are effectively off anyway */
  }
  if (!on) clearDraft();
}

/** Persist the notebook locally. Silently gives up if storage is unavailable. */
export function saveDraft(cells: NotebookCell[], tables: string[]): void {
  if (!isDraftEnabled()) return;
  const isEmpty = cells.every((c) => !c.source.trim());
  if (isEmpty) {
    clearDraft();
    return;
  }
  for (let level = 1; level <= 3; level++) {
    try {
      const draft: NotebookDraft = { cells: trim(cells, level), tables, savedAt: Date.now() };
      localStorage.setItem(KEY, JSON.stringify(draft));
      return;
    } catch {
      // Quota exceeded (or storage blocked) — retry with less, then give up.
    }
  }
}

/** The most recent draft, or null when there is nothing to restore. */
export function loadDraft(): NotebookDraft | null {
  try {
    const raw = localStorage.getItem(KEY);
    if (!raw) return null;
    const draft = JSON.parse(raw) as NotebookDraft;
    if (!Array.isArray(draft.cells) || !draft.cells.length) return null;
    if (draft.cells.every((c) => !c.source?.trim())) return null;
    return { cells: draft.cells, tables: draft.tables ?? [], savedAt: draft.savedAt ?? 0 };
  } catch {
    return null;
  }
}

export function clearDraft(): void {
  try {
    localStorage.removeItem(KEY);
  } catch {
    /* storage blocked — nothing to clear */
  }
}

/** "just now" / "2 hours ago" — used on the restore banner. */
export function describeAge(savedAt: number, now = Date.now()): string {
  const mins = Math.round((now - savedAt) / 60000);
  if (mins < 1) return 'just now';
  if (mins < 60) return `${mins} minute${mins === 1 ? '' : 's'} ago`;
  const hours = Math.round(mins / 60);
  if (hours < 24) return `${hours} hour${hours === 1 ? '' : 's'} ago`;
  const days = Math.round(hours / 24);
  return `${days} day${days === 1 ? '' : 's'} ago`;
}
